[app_labels]
netflix = [
    "nflxvideo.net",
    "*.nflxvideo.net",
]

twitch = [
    "ttvnw.net",
    "hls.ttvnw.net",
    "*.ttvnw.net",
    "*.hls.ttvnw.net",
]

zoom = [
    "zoom.us",
    "*.zoom.us",
]

microsoft_teams = [
    "teams.microsoft.com",
    "*.teams.microsoft.com",
]

facebook = [
    "facebook.com",
    "fbcdn.net",
    "*.facebook.com",
    "*.fbcdn.net",
]

twitter = [
    "twitter.com",
    "twimg.com",
    "*.twitter.com",
    "*.twimg.com",
]